export const wantedHeaders = [
  "SessionTime",
  "SessionTick",
  "IsOnTrack",
  "OnPitRoad",
  "PlayerTrackSurface",
  "SteeringWheelAngle",
  "Throttle",
  "Brake",
  "Clutch",
  "Gear",
  "RPM",
  "Lap",
  "LapCompleted",
  "LapDist",
  "LapDistPct",
  "Speed",
  "YawRate",
  "LatAccel",
  "LongAccel",
];

export const normalizedHeaders = [
  "sessionTimeSeconds",
  "sessionTick",
  "isOnTrack",
  "playerTrackSurface",
  "onPitRoad",
  "steeringWheelAngleRadians",
  "throttle",
  "brake",
  "clutch",
  "gear",
  "rpm",
  "lapNumber",
  "lapCompleted",
  "lapDistMeters",
  "lapDistPct",
  "speedMetersPerSecond",
  "yawRate",
  "latAccel",
  "longAccel",
];

export const rawToNormalizedChannelMap = {
  SessionTime: "sessionTimeSeconds",
  SessionTick: "sessionTick",
  IsOnTrack: "isOnTrack",
  PlayerTrackSurface: "playerTrackSurface",
  OnPitRoad: "onPitRoad",
  SteeringWheelAngle: "steeringWheelAngleRadians",
  Throttle: "throttle",
  Brake: "brake",
  Clutch: "clutch",
  Gear: "gear",
  RPM: "rpm",
  Lap: "lapNumber",
  LapCompleted: "lapCompleted",
  LapDist: "lapDistMeters",
  LapDistPct: "lapDistPct",
  Speed: "speedMetersPerSecond",
  YawRate: "yawRate",
  LatAccel: "latAccel",
  LongAccel: "longAccel",
} as const;
